SELECT noOfCopies,bookId FROM tbl_book_copies WHERE branchId=1; 
UPDATE tbl_library_branch SET branchName = 'Sharpstown',branchAddress='03169 Anhalt Circle' WHERE branchId=1;
SELECT branchName, branchAddress FROM tbl_library_branch WHERE branchId=1;
SELECT cardNo FROM tbl_borrower;
SELECT bookId, branchId, cardNo, dateOut, dueDate FROM tbl_book_loans GROUP BY cardNo;
SELECT name FROM tbl_borrower WHERE cardNo=1;
SELECT dueDate FROM tbl_book_loans WHERE cardNo=1 AND branchId=1;
DELETE FROM tbl_book_loans WHERE bookId=60 AND branchId=1 AND cardNo=1;
DELETE FROM tbl_book_copies WHERE bookId=61 AND branchId=1;
UPDATE tbl_book_copies SET noOfCopies = 17 WHERE bookId = 60 AND branchId = 1;
INSERT INTO tbl_book_authors (bookId, authorId) VALUES (1, 1);
SELECT bookId, title FROM tbl_book GROUP BY bookId;
SELECT bookId, authorId FROM tbl_book_authors GROUP BY bookId;
SELECT bookId,genre_id from tbl_book_genres GROUP BY bookID;
SELECT genre_name,genre_id from tbl_genre GROUP BY genre_id;
INSERT INTO tbl_genre (genre_id,genre_name) VALUES (10,'Tenth');
SELECT authorName,authorId FROM tbl_author GROUP BY authorId;
SELECT publisherName,publisherId from tbl_publisher GROUP BY publisherId;
SELECT phone from tbl_borrower;
DELETE FROM tbl_book WHERE bookId = 1001;